# **NUMPY**
*************************
NumPy stands for Numerical Python. It is a Python library designed for fast computation with numerical data, making it ideal for telecom data analysis.

In [2]:
import numpy as np

### Creating Arrays

In [8]:
# 1-D Array  
arr = np.array([199,249,399,199])
print(arr)

[199 249 399 199]


In [9]:
# 2-D Array
data = np.array([[101,199],[102,399]])
print(data)

[[101 199]
 [102 399]]


### Array Properties

In [10]:
print(arr.shape) # Size of array(rows, columns)
print(arr.ndim) # Number of dimensions
print(arr.dtype) # Data type (int32, float64)

(4,)
1
int64


### Basic Math Operations

In [11]:
recharges = np.array([199, 249, 399])
print(recharges + 10) # Add ₹10 bonus
print(recharges * 2) # Double the values
print(np.mean(recharges)) # Average recharge

[209 259 409]
[398 498 798]
282.3333333333333


### Useful Functions

In [14]:
print(np.min(arr)) # Minimum 
print(np.max(arr)) # Maximum
print(np.sum(arr)) # Total
print(np.std(arr)) # Standard Deviation

199
399
1046
81.967981553775


## ***Array Manipulation & Statistics***

### Indexing and Slicing: Access specific elements or subsets of arrays.

In [16]:
arr = np.array([199, 249, 399, 449, 499])
print(arr[0]) # First item
print(arr[1:4]) # Items from index 1 to 3

199
[249 399 449]


### Reshape Arrays: Change the shape of an array to organize data.

In [18]:
data = np.array([199, 249, 399, 499, 599, 699])
reshaped = data.reshape(2, 3)
print(reshaped)

[[199 249 399]
 [499 599 699]]


### Conditional Filtering: Filter arrays based on conditions.

In [20]:
arr = np.array([199, 249, 399, 149])
high = arr[arr > 200]
print(high) # Only values above ₹200

[249 399]


### Random and Range Functions: Generate sequences or random data.

In [22]:
print(np.arange(100, 600, 100)) # [100, 200, 300, 400, 500]
print(np.random.randint(100, 500, size = 5)) # Random recharge values

[100 200 300 400 500]
[273 154 406 179 207]


## ***Telecom Use Cases***
********************************************************

### Use case: Average Recharge Value

In [24]:
recharges = np.array([199, 249, 399, 149, 499])
avg = np.mean(recharges)
print("Average Recharge: ", avg)

Average Recharge:  299.0


### Use Case: Identify High Value Customers

In [27]:
amounts = np.array([199, 249, 999, 399, 799])
high_value = amounts[amounts > 500]
print("High Value: ", high_value)

High Value:  [999 799]


### Monthly Recharge Trends

In [29]:
january = np.array([150, 200, 220, 250])
february = np.array([180, 230, 210, 260])
diff = february - january
print("Monthly Growth: ", diff)

Monthly Growth:  [ 30  30 -10  10]


## ***Practice Projects***
********************************************

### Create an array of recharge amounts and calculate total and average.

In [31]:
recharges = np.array([199, 249, 399, 149, 499])
total = np.sum(recharges)
average = np.mean(recharges)
print("Total Recharge: ", total)
print("Average Recharge: ", average)

Total Recharge:  1495
Average Recharge:  299.0


### Filter out recharge values less than ₹200

In [33]:
recharges = np.array([199, 249, 399, 149, 499])
low_value = recharges[recharges >= 200]
print("Recharges >= ₹200: ", low_value)

Recharges >= ₹200:  [249 399 499]


### Simulate recharge values for 10 users using   np.random.randint()  

In [34]:
simulated_recharges = np.random.randint(100, 1000, size = 10)
print("Simulated Recharges: ", simulated_recharges)

Simulated Recharges:  [213 429 474 679 346 212 857 541 841 245]
